using ARP.ESG_ReportStudio.API.Reporting;
using ARP.ESG_ReportStudio.API.Services;

namespace SD.ProjectName.Tests.Products;

/// <summary>
/// Shared test utilities for export tests.
/// </summary>
public static class ExportTestHelpers
{
    public static void CreateTestOrganization(InMemoryReportStore store)
    {
        var request = new CreateOrganizationRequest
        {
            Name = "Test Corporation",
            LegalForm = "corporation",
            Country = "US",
            Identifier = "TEST123",
            CreatedBy = "test-user"
        };
        
        store.CreateOrganization(request);
    }
    
    public static void CreateTestOrganizationalUnit(InMemoryReportStore store)
    {
        var request = new CreateOrganizationalUnitRequest
        {
            Name = "Headquarters",
            ParentId = null,
            Description = "Main office",
            CreatedBy = "test-user"
        };
        
        store.CreateOrganizationalUnit(request);
    }

    public static void CreateTestConfiguration(InMemoryReportStore store)
    {
        CreateTestOrganization(store);
        CreateTestOrganizationalUnit(store);
    }
    
    /// <summary>
    /// Creates a simple in-memory localization service for testing.
    /// Returns English labels by default.
    /// </summary>
    public static ILocalizationService CreateTestLocalizationService()
    {
        return new TestLocalizationService();
    }
    
    private class TestLocalizationService : ILocalizationService
    {
        private readonly Dictionary<string, string> _labels = new()
        {
            ["label.table-of-contents"] = "Table of Contents",
            ["label.assumptions"] = "Assumptions",
            ["label.data-gaps"] = "Data Gaps",
            ["label.appendix-evidence"] = "Appendix: Evidence and Attachments",
            ["label.report-mode"] = "Report Mode:",
            ["label.report-scope"] = "Report Scope:",
            ["label.generated-by"] = "Generated By:",
            ["label.generated-at"] = "Generated At:",
            ["label.total-sections"] = "Total Sections:",
            ["label.variant"] = "Variant:",
            ["label.language"] = "Language:",
            ["label.category"] = "Category:",
            ["label.owner"] = "Owner:",
            ["label.status"] = "Status:",
            ["label.field"] = "Field",
            ["label.value"] = "Value",
            ["label.unit"] = "Unit",
            ["label.point-status"] = "Status",
            ["label.confidence-level"] = "Confidence Level:",
            ["label.reason"] = "Reason:"
        };
        
        public string GetLabel(string key, string? language = null) =>
            _labels.TryGetValue(key, out var label) ? label : key;
        
        public Dictionary<string, string> GetAllLabels(string language) =>
            new Dictionary<string, string>(_labels);
        
        public bool IsSupportedLanguage(string language) => language == "en-US";
        
        public IReadOnlyList<string> GetSupportedLanguages() => new[] { "en-US" };
        
        public string FormatDate(string date, string? language = null) => date;
        
        public string FormatNumber(decimal value, string? language = null) => value.ToString("N2");
    }
}
