using ARP.ESG_ReportStudio.API.Reporting;
using Xunit;

namespace SD.ProjectName.Tests.Products;

public class GapsAndImprovementsReportTests
{
    [Fact]
    public void GetGapsAndImprovementsReport_WithNoData_ReturnsEmptyReport()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var report = store.GetGapsAndImprovementsReport(null, null, "test-user");
        
        // Assert
        Assert.NotNull(report);
        Assert.NotNull(report.Summary);
        Assert.Equal(0, report.Summary.TotalGaps);
        Assert.Equal(0, report.Summary.TotalAssumptions);
        Assert.Equal(0, report.Summary.TotalSimplifications);
        Assert.Equal(0, report.Summary.TotalRemediationPlans);
        Assert.NotNull(report.AutoGeneratedNarrative);
        Assert.Contains("complete data", report.AutoGeneratedNarrative);
        Assert.Null(report.ManualNarrative);
        Assert.Empty(report.Sections);
    }

    [Fact]
    public void GetGapsAndImprovementsReport_GeneratesNarrativeWithCorrectStructure()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var report = store.GetGapsAndImprovementsReport(null, null, "test-user");
        
        // Assert
        Assert.NotNull(report.AutoGeneratedNarrative);
        Assert.Contains("# Gaps and Improvements", report.AutoGeneratedNarrative);
        Assert.Contains("## Executive Summary", report.AutoGeneratedNarrative);
        Assert.Contains("## Detailed Findings by Section", report.AutoGeneratedNarrative);
        Assert.Contains("## Conclusion", report.AutoGeneratedNarrative);
    }

    [Fact]
    public void GetGapsAndImprovementsReport_SetsCorrectTimestamp()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var report = store.GetGapsAndImprovementsReport(null, null, "test-user");
        
        // Assert
        Assert.NotNull(report.GeneratedAt);
        Assert.NotEmpty(report.GeneratedAt);
        Assert.Equal("test-user", report.GeneratedBy);
    }

    [Fact]
    public void GetGapsAndImprovementsReport_WithPeriodFilter_ReturnsReport()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - even with a non-existent period ID, should return a report
        var report = store.GetGapsAndImprovementsReport("period-1", null, "test-user");
        
        // Assert
        Assert.NotNull(report);
        Assert.Equal("period-1", report.PeriodId);
        Assert.NotNull(report.Summary);
    }
}
