using ARP.ESG_ReportStudio.API.Reporting;
using Xunit;

namespace SD.ProjectName.Tests.Products;

public class GapsAndImprovementsReportTests
{
    [Fact]
    public void GetGapsAndImprovementsReport_WithNoData_ReturnsEmptyReport()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var report = store.GetGapsAndImprovementsReport(null, null, "test-user");
        
        // Assert
        Assert.NotNull(report);
        Assert.NotNull(report.Summary);
        Assert.Equal(0, report.Summary.TotalGaps);
        Assert.Equal(0, report.Summary.TotalAssumptions);
        Assert.Equal(0, report.Summary.TotalSimplifications);
        Assert.Equal(0, report.Summary.TotalRemediationPlans);
        Assert.NotNull(report.AutoGeneratedNarrative);
        Assert.Contains("complete data", report.AutoGeneratedNarrative);
        Assert.Null(report.ManualNarrative);
        Assert.Empty(report.Sections);
    }

    [Fact]
    public void GetGapsAndImprovementsReport_GeneratesNarrativeWithCorrectStructure()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var report = store.GetGapsAndImprovementsReport(null, null, "test-user");
        
        // Assert
        Assert.NotNull(report.AutoGeneratedNarrative);
        Assert.Contains("# Gaps and Improvements", report.AutoGeneratedNarrative);
        Assert.Contains("## Executive Summary", report.AutoGeneratedNarrative);
        Assert.Contains("## Detailed Findings by Section", report.AutoGeneratedNarrative);
        Assert.Contains("## Conclusion", report.AutoGeneratedNarrative);
    }

    [Fact]
    public void GetGapsAndImprovementsReport_SetsCorrectTimestamp()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var report = store.GetGapsAndImprovementsReport(null, null, "test-user");
        
        // Assert
        Assert.NotNull(report.GeneratedAt);
        Assert.NotEmpty(report.GeneratedAt);
        Assert.Equal("test-user", report.GeneratedBy);
    }

    [Fact]
    public void GetGapsAndImprovementsReport_WithPeriodFilter_ReturnsReport()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - even with a non-existent period ID, should return a report
        var report = store.GetGapsAndImprovementsReport("period-1", null, "test-user");
        
        // Assert
        Assert.NotNull(report);
        Assert.Equal("period-1", report.PeriodId);
        Assert.NotNull(report.Summary);
    }

    [Fact]
    public void GetGapsDashboard_WithNoData_ReturnsEmptyDashboard()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act
        var dashboard = store.GetGapsDashboard(null, "all", null, null, null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.Empty(dashboard.Gaps);
        Assert.Equal(0, dashboard.Summary.TotalGaps);
        Assert.Equal(0, dashboard.Summary.OpenGaps);
        Assert.Equal(0, dashboard.Summary.ResolvedGaps);
        Assert.Equal(0, dashboard.TotalCount);
    }

    [Fact]
    public void GetGapsDashboard_WithAllStatus_ReturnsAllGaps()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - with "all" status should not filter
        var dashboard = store.GetGapsDashboard(null, "all", null, null, null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Summary);
        Assert.NotNull(dashboard.Gaps);
    }

    [Fact]
    public void GetGapsDashboard_WithOpenStatus_FiltersCorrectly()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - with "open" status
        var dashboard = store.GetGapsDashboard(null, "open", null, null, null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Summary);
    }

    [Fact]
    public void GetGapsDashboard_WithResolvedStatus_FiltersCorrectly()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - with "resolved" status
        var dashboard = store.GetGapsDashboard(null, "resolved", null, null, null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Summary);
    }

    [Fact]
    public void GetGapsDashboard_SortsByRisk_Descending()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - sort by risk descending (default)
        var dashboard = store.GetGapsDashboard(null, "all", null, null, null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Gaps);
    }

    [Fact]
    public void GetGapsDashboard_SortsByDueDate()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - sort by due date
        var dashboard = store.GetGapsDashboard(null, "all", null, null, null, "dueDate", "asc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Gaps);
    }

    [Fact]
    public void GetGapsDashboard_FiltersBy_Section()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - filter by section
        var dashboard = store.GetGapsDashboard(null, "all", "section-1", null, null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Gaps);
    }

    [Fact]
    public void GetGapsDashboard_FiltersBy_Owner()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - filter by owner
        var dashboard = store.GetGapsDashboard(null, "all", null, "user-1", null, "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Gaps);
    }

    [Fact]
    public void GetGapsDashboard_FiltersBy_DuePeriod()
    {
        // Arrange
        var store = new InMemoryReportStore();
        
        // Act - filter by due period
        var dashboard = store.GetGapsDashboard(null, "all", null, null, "Q1 2026", "risk", "desc", "test-user");
        
        // Assert
        Assert.NotNull(dashboard);
        Assert.NotNull(dashboard.Gaps);
    }
}


