import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useKV } from '@github/spark/hooks'
import { 
  ChartBar, 
  CheckCircle, 
  WarningCircle, 
  Clock, 
  ArrowCounterClockwise,
  FileText,
  ListChecks
} from '@phosphor-icons/react'
import type { 
  User, 
  ReportingPeriod, 
  GapsAndImprovementsReport 
} from '@/lib/types'
import { getGapsAndImprovementsReport, updateGapsNarrative } from '@/lib/api'

interface GapsAndImprovementsViewProps {
  currentUser: User
}

export default function GapsAndImprovementsView({ currentUser }: GapsAndImprovementsViewProps) {
  const [periods] = useKV<ReportingPeriod[]>('reporting-periods', [])
  
  const [report, setReport] = useState<GapsAndImprovementsReport | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  
  // Filters
  const [selectedPeriod, setSelectedPeriod] = useState<string>('all')
  
  // Narrative editing
  const [isEditingNarrative, setIsEditingNarrative] = useState(false)
  const [editedNarrative, setEditedNarrative] = useState('')
  const [isSavingNarrative, setIsSavingNarrative] = useState(false)
  
  const activePeriod = (periods || []).find(p => p.status === 'active')
  
  // Fetch report data when filters change
  useEffect(() => {
    const fetchReport = async () => {
      setIsLoading(true)
      setError(null)
      
      try {
        const periodId = selectedPeriod === 'all' ? activePeriod?.id : selectedPeriod
        const data = await getGapsAndImprovementsReport(periodId)
        setReport(data)
        setEditedNarrative(data.manualNarrative || data.autoGeneratedNarrative)
      } catch (err) {
        console.error('Failed to fetch gaps and improvements report:', err)
        setError('Failed to load report. Please try again.')
      } finally {
        setIsLoading(false)
      }
    }
    
    fetchReport()
  }, [selectedPeriod, activePeriod])
  
  const handleSaveNarrative = async () => {
    if (!report) return
    
    setIsSavingNarrative(true)
    try {
      await updateGapsNarrative({ 
        manualNarrative: editedNarrative !== report.autoGeneratedNarrative ? editedNarrative : undefined 
      })
      
      // Update local report with new manual narrative
      setReport({
        ...report,
        manualNarrative: editedNarrative !== report.autoGeneratedNarrative ? editedNarrative : undefined
      })
      setIsEditingNarrative(false)
    } catch (err) {
      console.error('Failed to save narrative:', err)
      setError('Failed to save narrative. Please try again.')
    } finally {
      setIsSavingNarrative(false)
    }
  }
  
  const handleRevertNarrative = () => {
    if (!report) return
    setEditedNarrative(report.autoGeneratedNarrative)
  }
  
  const displayNarrative = report?.manualNarrative || report?.autoGeneratedNarrative || ''
  const isUsingManualNarrative = !!report?.manualNarrative
  
  if (error) {
    return (
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold tracking-tight text-foreground">
            Gaps and Improvements
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Comprehensive view of gaps, estimates, and remediation plans
          </p>
        </div>
        
        <Card className="border-destructive">
          <CardContent className="pt-6">
            <p className="text-destructive">{error}</p>
          </CardContent>
        </Card>
      </div>
    )
  }
  
  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-2xl font-semibold tracking-tight text-foreground">
            Gaps and Improvements
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            Compile gaps, estimates, assumptions, and remediation plans into a report-ready section
          </p>
        </div>
      </div>
      
      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Filters</CardTitle>
          <CardDescription>
            Filter the report by reporting period
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <div className="flex-1">
              <label className="text-sm font-medium text-foreground mb-2 block">
                Reporting Period
              </label>
              <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
                <SelectTrigger>
                  <SelectValue placeholder="Select period" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Active Period</SelectItem>
                  {(periods || []).map(period => (
                    <SelectItem key={period.id} value={period.id}>
                      {period.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>
      
      {isLoading && (
        <Card>
          <CardContent className="pt-6">
            <p className="text-muted-foreground">Loading report...</p>
          </CardContent>
        </Card>
      )}
      
      {!isLoading && report && (
        <>
          {/* Summary Metrics */}
          <div className="grid gap-4 md:grid-cols-4">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                  <WarningCircle size={16} />
                  Gaps
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">
                  {report.summary.unresolvedGaps}
                  <span className="text-sm font-normal text-muted-foreground ml-1">
                    / {report.summary.totalGaps}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  {report.summary.resolvedGaps} resolved
                </p>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                  <FileText size={16} />
                  Assumptions
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">
                  {report.summary.activeAssumptions}
                  <span className="text-sm font-normal text-muted-foreground ml-1">
                    active
                  </span>
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  {report.summary.deprecatedAssumptions} deprecated
                </p>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                  <ChartBar size={16} />
                  Simplifications
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">
                  {report.summary.activeSimplifications}
                  <span className="text-sm font-normal text-muted-foreground ml-1">
                    active
                  </span>
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  of {report.summary.totalSimplifications} total
                </p>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                  <ListChecks size={16} />
                  Remediation
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">
                  {report.summary.completedRemediationPlans}
                  <span className="text-sm font-normal text-muted-foreground ml-1">
                    / {report.summary.totalRemediationPlans}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  {report.summary.overdueActions} overdue action(s)
                </p>
              </CardContent>
            </Card>
          </div>
          
          {/* Main Content Tabs */}
          <Tabs defaultValue="narrative" className="space-y-4">
            <TabsList>
              <TabsTrigger value="narrative">Narrative</TabsTrigger>
              <TabsTrigger value="details">Detailed View</TabsTrigger>
            </TabsList>
            
            <TabsContent value="narrative" className="space-y-4">
              <Card>
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div>
                      <CardTitle>Report Narrative</CardTitle>
                      <CardDescription>
                        {isUsingManualNarrative ? (
                          <span className="flex items-center gap-1 text-amber-600 dark:text-amber-500">
                            <WarningCircle size={14} weight="fill" />
                            Using manually edited narrative
                          </span>
                        ) : (
                          'Auto-generated narrative based on current data'
                        )}
                      </CardDescription>
                    </div>
                    <div className="flex gap-2">
                      {!isEditingNarrative && (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => {
                            setIsEditingNarrative(true)
                            setEditedNarrative(displayNarrative)
                          }}
                        >
                          Edit Narrative
                        </Button>
                      )}
                      {isEditingNarrative && (
                        <>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              setIsEditingNarrative(false)
                              setEditedNarrative(displayNarrative)
                            }}
                          >
                            Cancel
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={handleRevertNarrative}
                            disabled={editedNarrative === report.autoGeneratedNarrative}
                          >
                            <ArrowCounterClockwise size={16} className="mr-1" />
                            Revert to Auto
                          </Button>
                          <Button
                            size="sm"
                            onClick={handleSaveNarrative}
                            disabled={isSavingNarrative}
                          >
                            {isSavingNarrative ? 'Saving...' : 'Save'}
                          </Button>
                        </>
                      )}
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  {isEditingNarrative ? (
                    <Textarea
                      value={editedNarrative}
                      onChange={(e) => setEditedNarrative(e.target.value)}
                      className="min-h-[500px] font-mono text-sm"
                      placeholder="Enter narrative text..."
                    />
                  ) : (
                    <div className="prose prose-sm max-w-none dark:prose-invert">
                      <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                        {displayNarrative}
                      </pre>
                    </div>
                  )}
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="details" className="space-y-4">
              {report.sections.map(section => (
                <Card key={section.sectionId}>
                  <CardHeader>
                    <CardTitle className="text-lg">{section.sectionTitle}</CardTitle>
                    <CardDescription>
                      <Badge variant="outline" className="capitalize">
                        {section.category}
                      </Badge>
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {/* Gaps */}
                    {section.gaps.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-sm text-foreground mb-2">
                          Identified Gaps ({section.gaps.length})
                        </h4>
                        <div className="space-y-2">
                          {section.gaps.map((gapWithRem, idx) => (
                            <div key={idx} className="border border-border rounded-lg p-3">
                              <div className="flex items-start justify-between mb-2">
                                <div>
                                  <p className="font-medium text-sm text-foreground">
                                    {gapWithRem.gap.title}
                                  </p>
                                  <p className="text-sm text-muted-foreground mt-1">
                                    {gapWithRem.gap.description}
                                  </p>
                                </div>
                                <Badge variant={gapWithRem.gap.resolved ? 'default' : 'destructive'}>
                                  {gapWithRem.gap.resolved ? 'Resolved' : 'Open'}
                                </Badge>
                              </div>
                              
                              {gapWithRem.remediationPlan && (
                                <div className="mt-2 pt-2 border-t border-border">
                                  <p className="text-xs font-medium text-muted-foreground mb-1">
                                    Remediation Plan:
                                  </p>
                                  <p className="text-sm text-foreground">
                                    {gapWithRem.remediationPlan.plan.title}
                                  </p>
                                  <p className="text-xs text-muted-foreground mt-1">
                                    Target: {gapWithRem.remediationPlan.plan.targetPeriod} • 
                                    Owner: {gapWithRem.remediationPlan.plan.ownerName} • 
                                    {gapWithRem.remediationPlan.actions.length} action(s)
                                  </p>
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                    
                    {/* Assumptions */}
                    {section.assumptions.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-sm text-foreground mb-2">
                          Applied Assumptions ({section.assumptions.length})
                        </h4>
                        <div className="space-y-2">
                          {section.assumptions.map((assumpRef, idx) => (
                            <div key={idx} className="border border-border rounded-lg p-3">
                              <p className="font-medium text-sm text-foreground">
                                {assumpRef.assumption.title}
                              </p>
                              <p className="text-sm text-muted-foreground mt-1">
                                {assumpRef.assumption.description}
                              </p>
                              {assumpRef.linkedDataPointTitles.length > 0 && (
                                <p className="text-xs text-muted-foreground mt-2">
                                  Applied to: {assumpRef.linkedDataPointTitles.join(', ')}
                                </p>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                    
                    {/* Simplifications */}
                    {section.simplifications.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-sm text-foreground mb-2">
                          Scope Simplifications ({section.simplifications.length})
                        </h4>
                        <div className="space-y-2">
                          {section.simplifications.map((simpRef, idx) => (
                            <div key={idx} className="border border-border rounded-lg p-3">
                              <div className="flex items-start justify-between">
                                <div>
                                  <p className="font-medium text-sm text-foreground">
                                    {simpRef.simplification.title}
                                  </p>
                                  <p className="text-sm text-muted-foreground mt-1">
                                    {simpRef.simplification.description}
                                  </p>
                                </div>
                                <Badge variant="outline" className="capitalize">
                                  {simpRef.simplification.impactLevel} impact
                                </Badge>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                    
                    {/* Remediation Plans */}
                    {section.remediationPlans.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-sm text-foreground mb-2">
                          Remediation Plans ({section.remediationPlans.length})
                        </h4>
                        <div className="space-y-2">
                          {section.remediationPlans.map((planWithActions, idx) => (
                            <div key={idx} className="border border-border rounded-lg p-3">
                              <div className="flex items-start justify-between mb-2">
                                <div>
                                  <p className="font-medium text-sm text-foreground">
                                    {planWithActions.plan.title}
                                  </p>
                                  <p className="text-sm text-muted-foreground mt-1">
                                    {planWithActions.plan.description}
                                  </p>
                                </div>
                                <Badge variant="outline" className="capitalize">
                                  {planWithActions.plan.status}
                                </Badge>
                              </div>
                              <p className="text-xs text-muted-foreground">
                                Target: {planWithActions.plan.targetPeriod} • 
                                Owner: {planWithActions.plan.ownerName} • 
                                Priority: {planWithActions.plan.priority}
                              </p>
                              {planWithActions.actions.length > 0 && (
                                <div className="mt-2 pt-2 border-t border-border">
                                  <p className="text-xs font-medium text-muted-foreground mb-1">
                                    Actions ({planWithActions.actions.filter(a => a.status === 'completed').length}/{planWithActions.actions.length} completed):
                                  </p>
                                  <ul className="space-y-1">
                                    {planWithActions.actions.map((action, actionIdx) => (
                                      <li key={actionIdx} className="text-xs flex items-center gap-2">
                                        {action.status === 'completed' ? (
                                          <CheckCircle size={12} className="text-green-600" weight="fill" />
                                        ) : (
                                          <Clock size={12} className="text-muted-foreground" />
                                        )}
                                        <span className="text-foreground">{action.title}</span>
                                      </li>
                                    ))}
                                  </ul>
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                    
                    {section.gaps.length === 0 && 
                     section.assumptions.length === 0 && 
                     section.simplifications.length === 0 && 
                     section.remediationPlans.length === 0 && (
                      <p className="text-sm text-muted-foreground italic">
                        No gaps, assumptions, or simplifications identified for this section.
                      </p>
                    )}
                  </CardContent>
                </Card>
              ))}
              
              {report.sections.length === 0 && (
                <Card>
                  <CardContent className="pt-6">
                    <p className="text-muted-foreground">
                      No sections with gaps or improvements found for the selected period.
                    </p>
                  </CardContent>
                </Card>
              )}
            </TabsContent>
          </Tabs>
        </>
      )}
    </div>
  )
}
