// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD.ProjectName.Modules.Integrations.Infrastructure;

#nullable disable

namespace SD.ProjectName.Modules.Integrations.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260131045239_AddCanonicalDataModel")]
    partial class AddCanonicalDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DeprecatedInVersion")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("ExampleValues")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeprecated");

                    b.HasIndex("IsRequired");

                    b.HasIndex("EntityType", "SchemaVersion", "AttributeName")
                        .IsUnique();

                    b.ToTable("CanonicalAttributes", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportedByJobId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VendorExtensions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("ImportedByJobId");

                    b.HasIndex("IsApproved");

                    b.HasIndex("SchemaVersion");

                    b.HasIndex("EntityType", "SchemaVersion");

                    b.HasIndex("SourceSystem", "ExternalId");

                    b.ToTable("CanonicalEntities", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntityVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackwardCompatibleWithVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<string>("MigrationRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemaDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeprecated");

                    b.HasIndex("EntityType", "Version")
                        .IsUnique();

                    b.ToTable("CanonicalEntityVersions", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalAttribute")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("TargetEntityType")
                        .HasColumnType("int");

                    b.Property<int>("TargetSchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("TransformationParams")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransformationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsRequired");

                    b.HasIndex("ConnectorId", "TargetEntityType");

                    b.HasIndex("ConnectorId", "TargetEntityType", "TargetSchemaVersion");

                    b.ToTable("CanonicalMappings", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthenticationSecretRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AuthenticationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EndpointBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MappingConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("int");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("UseExponentialBackoff")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorType");

                    b.HasIndex("Status");

                    b.ToTable("Connectors", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.FinanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanonicalEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ExtractTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportJobId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MappedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalEntityId");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("EntityType");

                    b.HasIndex("ImportJobId");

                    b.HasIndex("IsApproved");

                    b.HasIndex("ConnectorId", "ExternalId")
                        .IsUnique();

                    b.ToTable("FinanceEntities", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.FinanceSyncRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedOverrideBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ConflictDetected")
                        .HasColumnType("bit");

                    b.Property<string>("ConflictResolution")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("FinanceEntityId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("OverwroteApprovedData")
                        .HasColumnType("bit");

                    b.Property<string>("RawData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConflictDetected");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("FinanceEntityId");

                    b.HasIndex("Status");

                    b.HasIndex("SyncedAt");

                    b.ToTable("FinanceSyncRecords", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.HREntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanonicalEntityId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MappedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalEntityId");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("EntityType");

                    b.HasIndex("IsApproved");

                    b.HasIndex("ConnectorId", "ExternalId")
                        .IsUnique();

                    b.ToTable("HREntities", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.HRSyncRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HREntityId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("OverwroteApprovedData")
                        .HasColumnType("bit");

                    b.Property<string>("RawData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("HREntityId");

                    b.HasIndex("Status");

                    b.HasIndex("SyncedAt");

                    b.ToTable("HRSyncRecords", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.IntegrationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("IntegrationLogs", (string)null);
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntity", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntityVersion", "Schema")
                        .WithMany("Entities")
                        .HasForeignKey("EntityType", "SchemaVersion")
                        .HasPrincipalKey("EntityType", "Version")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalMapping", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.FinanceEntity", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntity", "CanonicalEntity")
                        .WithMany()
                        .HasForeignKey("CanonicalEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalEntity");

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.FinanceSyncRecord", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.FinanceEntity", "FinanceEntity")
                        .WithMany()
                        .HasForeignKey("FinanceEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connector");

                    b.Navigation("FinanceEntity");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.HREntity", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntity", "CanonicalEntity")
                        .WithMany()
                        .HasForeignKey("CanonicalEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalEntity");

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.HRSyncRecord", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.HREntity", "HREntity")
                        .WithMany()
                        .HasForeignKey("HREntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connector");

                    b.Navigation("HREntity");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.IntegrationLog", b =>
                {
                    b.HasOne("SD.ProjectName.Modules.Integrations.Domain.Entities.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("SD.ProjectName.Modules.Integrations.Domain.Entities.CanonicalEntityVersion", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
