using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ARP.ESG_ReportStudio.API.Reporting;

namespace ARP.ESG_ReportStudio.API.Services;

/// <summary>
/// Service for exporting generated reports to PDF format with title page, TOC, and page numbering.
/// </summary>
public sealed class PdfExportService : IPdfExportService
{
    public PdfExportService()
    {
        // Set QuestPDF license type for community/commercial use
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GeneratePdf(GeneratedReport report, PdfExportOptions? options = null)
    {
        options ??= new PdfExportOptions();
        
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));
                
                page.Content().Column(column =>
                {
                    // Title page
                    if (options.IncludeTitlePage)
                    {
                        column.Item().PageBreak();
                        column.Item().Element(c => ComposeTitlePage(c, report, options));
                    }
                    
                    // Table of contents
                    if (options.IncludeTableOfContents && report.Sections.Count > 0)
                    {
                        column.Item().PageBreak();
                        column.Item().Element(c => ComposeTableOfContents(c, report));
                    }
                    
                    // Report content
                    if (report.Sections.Count > 0)
                    {
                        column.Item().PageBreak();
                        column.Item().Element(c => ComposeReportContent(c, report));
                    }
                });
                
                // Footer with page numbers
                if (options.IncludePageNumbers)
                {
                    page.Footer().AlignCenter().DefaultTextStyle(x => x.FontSize(9)).Text(text =>
                    {
                        text.CurrentPageNumber();
                        text.Span(" / ");
                        text.TotalPages();
                    });
                }
            });
        });

        return document.GeneratePdf();
    }

    public string GenerateFilename(GeneratedReport report, string? variantName = null)
    {
        var companyName = SanitizeFilename(report.Organization?.Name ?? "ESG-Report");
        var periodName = SanitizeFilename(report.Period.Name);
        var generatedDate = DateTime.TryParse(report.GeneratedAt, out var dt) 
            ? dt.ToString("yyyy-MM-dd") 
            : DateTime.UtcNow.ToString("yyyy-MM-dd");
        
        var parts = new List<string> { companyName, periodName };
        
        if (!string.IsNullOrWhiteSpace(variantName))
        {
            parts.Add(SanitizeFilename(variantName));
        }
        
        parts.Add(generatedDate);
        
        return $"{string.Join("_", parts)}.pdf";
    }

    private void ComposeTitlePage(IContainer container, GeneratedReport report, PdfExportOptions options)
    {
        container.Column(column =>
        {
            column.Spacing(20);
            
            // Organization name
            column.Item().AlignCenter().Text(report.Organization?.Name ?? "ESG Responsibility Report")
                .FontSize(24).Bold();
            
            // Report period
            column.Item().AlignCenter().Text(report.Period.Name)
                .FontSize(18).SemiBold();
            
            // Date range
            column.Item().AlignCenter().Text($"{report.Period.StartDate} to {report.Period.EndDate}")
                .FontSize(14);
            
            // Variant name if provided
            if (!string.IsNullOrWhiteSpace(options.VariantName))
            {
                column.Item().AlignCenter().Text($"Variant: {options.VariantName}")
                    .FontSize(14).Italic();
            }
            
            column.Item().PaddingTop(40);
            
            // Report metadata
            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(150);
                    columns.RelativeColumn();
                });
                
                table.Cell().Text("Report Mode:").SemiBold();
                table.Cell().Text(report.Period.ReportingMode);
                
                table.Cell().Text("Report Scope:").SemiBold();
                table.Cell().Text(report.Period.ReportScope);
                
                table.Cell().Text("Generated By:").SemiBold();
                table.Cell().Text(report.GeneratedByName);
                
                table.Cell().Text("Generated At:").SemiBold();
                table.Cell().Text(FormatDateTime(report.GeneratedAt));
                
                table.Cell().Text("Total Sections:").SemiBold();
                table.Cell().Text(report.Sections.Count.ToString());
            });
        });
    }

    private void ComposeTableOfContents(IContainer container, GeneratedReport report)
    {
        container.Column(column =>
        {
            column.Item().Text("Table of Contents").FontSize(18).Bold();
            column.Item().PaddingTop(10);
            
            foreach (var section in report.Sections.OrderBy(s => s.Section.Order))
            {
                column.Item().PaddingTop(5).Row(row =>
                {
                    row.AutoItem().Width(40).Text($"{section.Section.Order}.");
                    row.RelativeItem().Text(section.Section.Title);
                });
            }
        });
    }

    private void ComposeReportContent(IContainer container, GeneratedReport report)
    {
        container.Column(column =>
        {
            foreach (var section in report.Sections.OrderBy(s => s.Section.Order))
            {
                column.Item().Element(c => ComposeSection(c, section));
                column.Item().PaddingBottom(20);
            }
        });
    }

    private void ComposeSection(IContainer container, GeneratedReportSection section)
    {
        container.Column(column =>
        {
            // Section header
            column.Item().PaddingBottom(10).Column(headerColumn =>
            {
                headerColumn.Item().Text(section.Section.Title).FontSize(16).Bold();
                
                if (!string.IsNullOrWhiteSpace(section.Section.Description))
                {
                    headerColumn.Item().PaddingTop(5).Text(section.Section.Description)
                        .FontSize(10).Italic();
                }
                
                // Section metadata
                headerColumn.Item().PaddingTop(5).Row(row =>
                {
                    row.AutoItem().Text($"Category: {section.Section.Category}").FontSize(9);
                    row.AutoItem().PaddingLeft(15).Text($"Owner: {section.Owner?.Name ?? "Unassigned"}").FontSize(9);
                    row.AutoItem().PaddingLeft(15).Text($"Status: {section.Section.Status}").FontSize(9);
                });
            });
            
            // Data points
            if (section.DataPoints.Count > 0)
            {
                column.Item().Element(c => ComposeDataPoints(c, section.DataPoints));
            }
            
            // Assumptions
            if (section.Assumptions.Count > 0)
            {
                column.Item().PaddingTop(10).Element(c => ComposeAssumptions(c, section.Assumptions));
            }
            
            // Gaps
            if (section.Gaps.Count > 0)
            {
                column.Item().PaddingTop(10).Element(c => ComposeGaps(c, section.Gaps));
            }
        });
    }

    private void ComposeDataPoints(IContainer container, List<DataPointSnapshot> dataPoints)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(2);
                columns.RelativeColumn(3);
                columns.RelativeColumn(1);
                columns.RelativeColumn(1);
            });
            
            // Header
            table.Header(header =>
            {
                header.Cell().Background(Colors.Grey.Lighten2).Padding(5).Text("Title").SemiBold();
                header.Cell().Background(Colors.Grey.Lighten2).Padding(5).Text("Value").SemiBold();
                header.Cell().Background(Colors.Grey.Lighten2).Padding(5).Text("Unit").SemiBold();
                header.Cell().Background(Colors.Grey.Lighten2).Padding(5).Text("Status").SemiBold();
            });
            
            // Data rows with alternating background
            var rowIndex = 0;
            foreach (var dp in dataPoints)
            {
                var bgColor = rowIndex % 2 == 0 ? Colors.White : Colors.Grey.Lighten4;
                
                table.Cell().Background(bgColor).Padding(5).Text(dp.Title ?? "").FontSize(10);
                table.Cell().Background(bgColor).Padding(5).Text(dp.Value ?? "-").FontSize(10);
                table.Cell().Background(bgColor).Padding(5).Text(dp.Unit ?? "-").FontSize(10);
                table.Cell().Background(bgColor).Padding(5).Text(dp.Status ?? "-").FontSize(10);
                
                rowIndex++;
            }
        });
    }

    private void ComposeAssumptions(IContainer container, List<AssumptionRecord> assumptions)
    {
        container.Column(column =>
        {
            column.Item().Background(Colors.Orange.Lighten4).Padding(8).Column(assumptionColumn =>
            {
                assumptionColumn.Item().Text("Assumptions").FontSize(12).SemiBold();
                
                foreach (var assumption in assumptions)
                {
                    assumptionColumn.Item().PaddingTop(5).Text(text =>
                    {
                        text.Span("• ").SemiBold();
                        text.Span($"{assumption.Description ?? "No description"}");
                        if (!string.IsNullOrWhiteSpace(assumption.ConfidenceLevel))
                        {
                            text.Span($" (Confidence: {assumption.ConfidenceLevel})").Italic().FontSize(9);
                        }
                    });
                }
            });
        });
    }

    private void ComposeGaps(IContainer container, List<GapRecord> gaps)
    {
        container.Column(column =>
        {
            column.Item().Background(Colors.Red.Lighten4).Padding(8).Column(gapColumn =>
            {
                gapColumn.Item().Text("Data Gaps").FontSize(12).SemiBold();
                
                foreach (var gap in gaps)
                {
                    gapColumn.Item().PaddingTop(5).Text(text =>
                    {
                        text.Span("• ").SemiBold();
                        text.Span($"{gap.Description ?? "No description"}");
                        if (!string.IsNullOrWhiteSpace(gap.MissingReason))
                        {
                            text.Span($" (Reason: {gap.MissingReason})").Italic().FontSize(9);
                        }
                    });
                }
            });
        });
    }

    private string FormatDateTime(string? isoDateTime)
    {
        if (string.IsNullOrWhiteSpace(isoDateTime))
        {
            return DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC");
        }
        
        if (DateTime.TryParse(isoDateTime, out var dt))
        {
            return dt.ToString("yyyy-MM-dd HH:mm:ss UTC");
        }
        
        return isoDateTime;
    }

    private string SanitizeFilename(string filename)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var sanitized = string.Join("_", filename.Split(invalid, StringSplitOptions.RemoveEmptyEntries));
        return sanitized.Trim().Replace(" ", "_");
    }
}
